// packages/react/src/components/HotKeysManager.tsx
import {
	HotKeysManagerInstance,
	type IHotKeysManagerOptions,
} from "@ez-kits/hot-keys-core";
import { useEffect, useState } from "react";
import { HotKeysManagerContext } from "src/contexts/HotKeysManagerContext";

interface HotKeysManagerProps extends IHotKeysManagerOptions {
	children: React.ReactNode;
}

export function HotKeysManager({ children, ...options }: HotKeysManagerProps) {
	const [hotKeysManager] = useState(() => new HotKeysManagerInstance(options));
	hotKeysManager.updateOptions(options);

	useEffect(() => {
		return hotKeysManager.mount();
	}, [hotKeysManager]);

	return (
		<HotKeysManagerContext.Provider value={hotKeysManager}>
			{children}
		</HotKeysManagerContext.Provider>
	);
}

// packages/solid/src/components/HotKeysManager.tsx
import {
	HotKeysManagerInstance,
	type IHotKeysManagerOptions,
} from "@ez-kits/hot-keys-core";
import { createEffect, onCleanup, splitProps, type JSX } from "solid-js";
import { HotKeysManagerContext } from "src/contexts/HotKeysManagerContext";

interface HotKeysManagerProps extends IHotKeysManagerOptions {
	children: JSX.Element;
}

export function HotKeysManager(props: HotKeysManagerProps) {
	const [, otherProps] = splitProps(props, ["children"]);
	const hotKeysManager = new HotKeysManagerInstance(otherProps);

	hotKeysManager.updateOptions(otherProps);

	createEffect(() => {
		hotKeysManager.updateOptions(otherProps);
	});

	createEffect(() => {
		hotKeysManager.mount();

		onCleanup(() => {
			hotKeysManager.unmount();
		});
	});

	return (
		<HotKeysManagerContext.Provider value={hotKeysManager}>
			{props.children}
		</HotKeysManagerContext.Provider>
	);
}
