// packages/solid/src/hooks/useHotKeys.ts
import {
	registerHotKeysFromRecord,
	type HotKeyHandler,
} from "@ez-kits/hot-keys-core";
import { createEffect, onCleanup } from "solid-js";
import { useHotKeysManagerContext } from "src/hooks";
import type { MaybeAccessor } from "src/types";
import { getValueFromAccessor } from "src/utilities";

export interface UseHotKeysOptions {
	hotKeys: MaybeAccessor<Record<string, HotKeyHandler>>;
	/**
	 * The separator of the hotkeys
	 * @default ","
	 */
	hotKeysSeparator?: MaybeAccessor<string>;
	scopeName: MaybeAccessor<string>;
}

export function useHotKeys(options: UseHotKeysOptions) {
	const hotKeysManager = useHotKeysManagerContext();

	createEffect(() => {
		const unregister = registerHotKeysFromRecord(
			hotKeysManager,
			getValueFromAccessor(options.scopeName),
			getValueFromAccessor(options.hotKeys),
			getValueFromAccessor(options.hotKeysSeparator) || ","
		);

		onCleanup(() => {
			unregister();
		});
	});
}

// packages/react/src/hooks/useHotKeys.ts
import {
	registerHotKeysFromRecord,
	type HotKeyHandler,
} from "@ez-kits/hot-keys-core";
import { useEffect } from "react";
import { useHotKeysManagerContext } from "src/hooks";

export interface UseHotKeysOptions {
	hotKeys: Record<string, HotKeyHandler>;
	/**
	 * The separator of the hotkeys
	 * @default ","
	 */
	hotKeysSeparator?: string;
	scopeName: string;
}

export function useHotKeys(options: UseHotKeysOptions) {
	const hotKeysManager = useHotKeysManagerContext();

	useEffect(() => {
		return registerHotKeysFromRecord(
			hotKeysManager,
			options.scopeName,
			options.hotKeys,
			options.hotKeysSeparator || ","
		);
	}, [
		hotKeysManager,
		options.hotKeys,
		options.scopeName,
		options.hotKeysSeparator,
	]);
}
